mutation create_player($name: String!) {
  CreateEnjinUser(name: $name) {
    id
    accessTokens
    identities {
      linkingCode
      linkingCodeQr
      wallet {
        ethAddress
      }
    }
  }
}
